# -*- coding: utf-8 -*-
"""life expctancy analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zfIbAuSuyUtoYd5xaRbPvHoKr1OpYPFM
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_percentage_error

# 1. LOAD AND CLEAN NAMES
df = pd.read_csv('Life_Expectancy_Data.csv')
df.columns = df.columns.str.strip() # This fixes the trailing spaces

# TASK 1: FEATURE ENGINEERING
def get_pop_range(p):
    if p < 30000: return 'Small'
    elif p < 100000: return 'Medium'
    else: return 'Large'

df['Population_Range'] = df['Population'].apply(get_pop_range)
df['Lifestyle'] = df['Alcohol'] * df['BMI']
df['Economy'] = df['Population'] * df['GDP']
df['Death_Ratio'] = df['Adult Mortality'] / df['infant deaths'].replace(0, 1)

# TASK 2: CLEANING & IMPUTATION
# We fill missing values with the median so we don't lose too much data
numeric_cols = df.select_dtypes(include=[np.number]).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

# TASK 3: CORRELATION HEATMAP (Threshold 0.75)
plt.figure(figsize=(12, 10))
corr_matrix = df.select_dtypes(include=[np.number]).corr().abs()
sns.heatmap(corr_matrix, annot=True, cmap='RdYlGn', fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

# Drop columns > 0.75 correlation (but keep Schooling and Target)
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
to_drop = [column for column in upper.columns if any(upper[column] > 0.75)
           and column not in ['Life expectancy', 'Schooling']]
df_model = df.drop(columns=to_drop)

# TASK 4: BOXPLOTS FOR OUTLIERS
plt.figure(figsize=(12, 6))
sns.boxplot(data=df_model[['Life expectancy', 'Adult Mortality', 'Schooling']])
plt.title("Checking for Outliers")
plt.show()

# TASK 6: LINEAR REGRESSION
X = df_model.select_dtypes(include=[np.number]).drop(columns=['Life expectancy'])
y = df_model['Life expectancy']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# PRINT PERFORMANCE METRICS
print(f"--- MODEL PERFORMANCE ---")
print(f"R2 Score: {r2_score(y_test, y_pred):.4f}")
print(f"RMSE: {np.sqrt(mean_squared_error(y_test, y_pred)):.4f}")
print(f"MAPE: {mean_absolute_percentage_error(y_test, y_pred):.4f}")

# RESIDUAL PLOTS
plt.figure(figsize=(10, 5))
plt.scatter(y_test, y_pred, alpha=0.5)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], '--r')
plt.title("Residual Scatter Plot (Actual vs Predicted)")
plt.xlabel("Actual Life Expectancy")
plt.ylabel("Predicted")
plt.show()

plt.figure(figsize=(10, 5))
sns.histplot(y_test - y_pred, kde=True)
plt.title("Residual Histogram")
plt.show()